const currentDate = new Date();
const currentYear = currentDate.getFullYear();

export const financialFlowTypes = {
  investment: {
    saving_account: {
      label: "Saving Account",
      icon: "🏦",
      parameters: [
        {
          id: "start_year",
          label: "Start Year",
          type: "number",
          required: true,
          min: currentYear,
          step: 1,
          group: "dates",
        },
        {
          id: "start_month",
          label: "Start Month",
          type: "number",
          required: true,
          min: 1,
          max: 12,
          step: 1,
          group: "dates",
        },
        {
          id: "end_year",
          label: "End Year",
          type: "number",
          required: true,
          min: currentYear + 1,
          step: 1,
          validate: (formData) => {
            if (formData.start_year >= formData.end_year) {
              return `End year must be greater than start year`;
            }
            return true;
          },
          group: "dates",
        },
        {
          id: "end_month",
          label: "End Month",
          type: "number",
          required: true,
          min: 1,
          max: 12,
          step: 1,
          group: "dates",
        },
        {
          id: "yearly_interest_rate",
          label: "Yearly Interest Rate (%)",
          type: "number",
          required: true,
          min: 0,
          max: 100,
          step: 0.1,
          group: "investment",
        },
        {
          id: "initial_investment",
          label: "Initial investment (€)",
          type: "number",
          required: false,
          min: 0,
          step: 50,
          max: 22950,
          group: "investment",
        },
        {
          id: "monthly_investment",
          label: "Monthly investment (€)",
          type: "number",
          required: false,
          min: 0,
          step: 100,
          group: "investment",
        },
      ],
    },
    stock_exchange: {
      label: "Stock Exchange",
      icon: "📈",
      parameters: [
        {
          id: "start_year",
          label: "Start Year",
          type: "number",
          required: true,
          min: currentYear,
          step: 1,
          group: "dates",
        },
        {
          id: "start_month",
          label: "Start Month",
          type: "number",
          required: true,
          min: 1,
          max: 12,
          step: 1,
          group: "dates",
        },
        {
          id: "end_year",
          label: "End Year",
          type: "number",
          required: true,
          min: currentYear + 1,
          step: 1,
          validate: (formData) => {
            if (formData.start_year >= formData.end_year) {
              return `End year must be greater than start year`;
            }
            return true;
          },
          group: "dates",
        },
        {
          id: "end_month",
          label: "End Month",
          type: "number",
          required: true,
          min: 1,
          max: 12,
          step: 1,
          group: "dates",
        },
        {
          id: "yearly_interest_rate",
          label: "Yearly Interest Rate (%)",
          type: "number",
          default: 8,
          required: true,
          min: 0,
          max: 100,
          step: 0.1,
          group: "investment",
        },
        {
          id: "initial_investment",
          label: "Initial investment (€)",
          type: "number",
          required: false,
          min: 0,
          step: 100,
          default: 0,
          group: "investment",
        },
        {
          id: "monthly_investment",
          label: "Monthly investment (€)",
          type: "number",
          required: false,
          min: 0,
          step: 100,
          default: 0,
          group: "investment",
        },
      ],
    },
    real_estate: {
      label: "Real Estate",
      icon: "🏠",
      parameters: [
        {
          id: "start_year",
          label: "Purchase Year",
          type: "number",
          required: true,
          min: 1900,
          step: 1,
          group: "dates",
        },
        {
          id: "start_month",
          label: "Purchase Month",
          type: "number",
          required: true,
          min: 1,
          max: 12,
          step: 1,
          group: "dates",
        },
        {
          id: "end_year",
          label: "Year of sale",
          type: "number",
          required: true,
          min: 1900,
          step: 1,
          group: "dates",
        },
        {
          id: "end_month",
          label: "Month of sale",
          type: "number",
          required: true,
          min: 1,
          max: 12,
          step: 1,
          group: "dates",
        },
        {
          id: "property_value",
          label: "Property Value (€)",
          type: "number",
          required: true,
          min: 0,
          step: 1000,
          group: "project amount",
        },
        {
          id: "work_renovation",
          label: "Work / Renovation (€)",
          type: "number",
          min: 0,
          step: 100,
          group: "project amount",
        },
        {
          id: "notary_fees",
          label: "Notary Fees (€)",
          type: "number",
          min: 0,
          step: 100,
          group: "project amount",
        },
        {
          id: "agency_fees",
          label: "Agency Fees (€)",
          type: "number",
          min: 0,
          step: 100,
          group: "project amount",
        },
        {
          id: "other_fees",
          label: "Other Fees (€)",
          type: "number",
          min: 0,
          step: 100,
          group: "project amount",
        },
        {
          id: "loan_rate",
          label: "Loan Rate (%)",
          type: "number",
          required: true,
          min: 0,
          max: 100,
          step: 0.1,
          group: "financing",
        },
        {
          id: "insurance_rate",
          label: "Insurance Rate (%)",
          type: "number",
          required: true,
          min: 0,
          max: 100,
          step: 0.1,
          group: "financing",
        },
        {
          id: "loan_amount",
          label: "Loan Amount (€)",
          type: "number",
          required: true,
          min: 0,
          step: 1000,
          group: "financing",
        },
        {
          id: "loan_duration",
          label: "Loan Duration (years)",
          type: "number",
          required: true,
          min: 1,
          step: 1,
          group: "financing",
        },
        {
          id: "personal_contribution",
          label: "Personal Contribution (€)",
          type: "number",
          required: true,
          min: 0,
          step: 100,
          group: "financing",
        },
        {
          id: "early_repayment_fees",
          label: "Early Repayment Fees (%)",
          type: "number",
          required: true,
          min: 0,
          max: 100,
          step: 0.1,
          group: "financing",
        },
        {
          id: "yearly_index",
          label: "Property annual increase (%)",
          type: "number",
          required: true,
          min: 0,
          max: 100,
          step: 0.1,
          group: "other",
        },
        {
          id: "monthly_charges",
          label: "Monthly Charges (€)",
          type: "number",
          required: true,
          min: 0,
          step: 100,
          group: "charges and taxes",
        },
        {
          id: "property_tax",
          label: "Property Tax (€)",
          type: "number",
          required: true,
          min: 0,
          step: 100,
          group: "charges and taxes",
        },
      ],
    },
    rental_investment: {
      label: "Rental investment",
      icon: "🏢",
      parameters: [
        {
          id: "start_year",
          label: "Purchase Year",
          type: "number",
          required: true,
          min: 1900,
          step: 1,
          group: "dates",
        },
        {
          id: "start_month",
          label: "Purchase Month",
          type: "number",
          required: true,
          min: 1,
          max: 12,
          step: 1,
          group: "dates",
        },
        {
          id: "end_year",
          label: "Year of sale",
          type: "number",
          required: true,
          min: 1900,
          step: 1,
          group: "dates",
        },
        {
          id: "end_month",
          label: "Month of sale",
          type: "number",
          required: true,
          min: 1,
          max: 12,
          step: 1,
          group: "dates",
        },
        {
          id: "property_value",
          label: "Property Value (€)",
          type: "number",
          required: true,
          min: 0,
          step: 1000,
          group: "project amount",
        },
        {
          id: "work_renovation",
          label: "Work / Renovation (€)",
          type: "number",
          min: 0,
          step: 100,
          group: "project amount",
        },
        {
          id: "notary_fees",
          label: "Notary Fees (€)",
          type: "number",
          min: 0,
          step: 100,
          group: "project amount",
        },
        {
          id: "agency_fees",
          label: "Agency Fees (€)",
          type: "number",
          min: 0,
          step: 100,
          group: "project amount",
        },
        {
          id: "other_fees",
          label: "Other Fees (€)",
          type: "number",
          min: 0,
          step: 100,
          group: "project amount",
        },
        {
          id: "loan_rate",
          label: "Loan Rate (%)",
          type: "number",
          required: true,
          min: 0,
          max: 100,
          step: 0.1,
          group: "financing",
        },
        {
          id: "insurance_rate",
          label: "Insurance Rate (%)",
          type: "number",
          required: true,
          min: 0,
          max: 100,
          step: 0.1,
          group: "financing",
        },
        {
          id: "loan_amount",
          label: "Loan Amount (€)",
          type: "number",
          required: true,
          min: 0,
          step: 1000,
          group: "financing",
        },
        {
          id: "loan_duration",
          label: "Loan Duration (years)",
          type: "number",
          required: true,
          min: 1,
          step: 1,
          group: "financing",
        },
        {
          id: "personal_contribution",
          label: "Personal Contribution (€)",
          type: "number",
          required: true,
          min: 0,
          step: 100,
          group: "financing",
        },
        {
          id: "early_repayment_fees",
          label: "Early Repayment Fees (%)",
          type: "number",
          required: true,
          min: 0,
          max: 100,
          step: 0.1,
          group: "financing",
        },
        {
          id: "monthly_charges",
          label: "Monthly Charges (€)",
          type: "number",
          required: true,
          min: 0,
          step: 100,
          group: "charges and taxes",
        },
        {
          id: "property_tax",
          label: "Property Tax (€)",
          type: "number",
          required: true,
          min: 0,
          step: 100,
          group: "charges and taxes",
        },
        {
          id: "rental_including_charges",
          label: "Monthly Rental Including Charges (€)",
          type: "number",
          required: true,
          group: "rental",
        },
        {
          id: "occupancy_rate",
          label: "Occupancy Rate (%)",
          type: "number",
          required: true,
          min: 0,
          max: 100,
          step: 0.1,
          group: "rental",
        },
        {
          id: "yearly_index",
          label: "Property annual increase (%)",
          type: "number",
          required: true,
          min: 0,
          max: 100,
          step: 0.1,
          group: "other",
        },
      ],
    },
  },

  charges: {
    rental_personal_use: {
      id: "rental_personal_use",
      label: "Rental (PR)",
      icon: "🏡",
      parameters: [
        {
          id: "start_year",
          label: "Start Year",
          type: "number",
          required: true,
          min: currentYear,
          step: 1,
          group: "dates",
        },

        {
          id: "start_month",
          label: "Start Month",
          type: "number",
          required: true,
          min: 1,
          max: 12,
          step: 1,
          group: "dates",
        },
        {
          id: "end_year",
          label: "End Year",
          type: "number",
          required: true,
          min: currentYear + 1,
          step: 1,
          validate: (formData) => {
            if (formData.start_year >= formData.end_year) {
              return `End year must be greater than start year`;
            }
            return true;
          },
          group: "dates",
        },
        {
          id: "end_month",
          label: "End Month",
          type: "number",
          required: true,
          min: 1,
          max: 12,
          step: 1,
          group: "dates",
        },
        {
          id: "rent_including_charges",
          label: "Rent including Charges",
          type: "number",
          required: true,
          min: 0,
          step: 10,
          group: "rental",
        },
      ],
    },
  },

  cash_inflow: {
    income: {
      id: "income",
      label: "Income",
      icon: "💸",
      parameters: [
        {
          id: "start_year",
          label: "Start Year",
          type: "number",
          required: true,
          min: currentYear,
          step: 1,
          group: "dates",
        },
        {
          id: "start_month",
          label: "Start Month",
          type: "number",
          required: true,
          min: 1,
          max: 12,
          step: 1,
          group: "dates",
        },
        {
          id: "end_year",
          label: "End Year",
          type: "number",
          required: true,
          min: currentYear,
          step: 1,
          group: "dates",
        },
        {
          id: "end_month",
          label: "End Month",
          type: "number",
          required: true,
          min: 1,
          max: 12,
          step: 1,
          group: "dates",
        },
        {
          id: "income",
          label: "Monthly Income",
          type: "number",
          required: true,
          min: 0,
          step: 10,
          group: "income",
        },
      ],
    },
    one_off_income: {
      id: "one_off_income",
      label: "One Off Income",
      icon: "💸",
      parameters: [
        {
          id: "year",
          label: "Year",
          type: "number",
          required: true,
          min: currentYear,
          step: 1,
          group: "dates",
        },
        {
          id: "month",
          label: "Month",
          type: "number",
          required: true,
          min: 1,
          max: 12,
          step: 1,
          group: "dates",
        },
        {
          id: "value",
          label: "Value",
          type: "number",
          required: true,
          min: 0,
          step: 10,
          group: "income",
        },
      ],
    },
  },
};
