const placementStyles = {
  cash: {
    label: "Cash",
    key: "cash",
    borderWidth: 2,
    borderColor: "rgba(133, 119, 122, 1)",
    backgroundColor: "rgba(133, 119, 122, 0.3)",
    fill: true,
    tension: 0.1,
    stack: "stack1",
    order: 2,
    pointRadius: 0,
    pointHoverRadius: 5,
    pointBackgroundColor: "rgba(133, 119, 122, 1)",
  },
  savings: {
    label: "Savings",
    key: "savings",
    borderWidth: 2,
    borderColor: "rgba(64, 164, 164, 1)",
    backgroundColor: "rgba(64, 164, 164, 0.3)",
    fill: true,
    tension: 0.1,
    stack: "stack1",
    order: 1,
    pointRadius: 0,
    pointHoverRadius: 5,
    pointBackgroundColor: "rgba(64, 164, 164, 1)",
  },
  stock_exchange: {
    label: "Stock exchange",
    key: "stock_exchange",
    borderWidth: 2,
    borderColor: "rgba(66, 164, 64, 1)",
    backgroundColor: "rgba(66, 164, 64, 0.3)",
    fill: true,
    tension: 0.1,
    stack: "stack1",
    order: 1,
    pointRadius: 0,
    pointHoverRadius: 5,
    pointBackgroundColor: "rgba(66, 164, 64, 1)",
  },
  net_real_estate: {
    label: "Real estate net worth",
    key: "net_real_estate",
    borderWidth: 2,
    borderColor: "rgba(164, 130, 64, 1)",
    backgroundColor: "rgba(164, 130, 64, 0.3)",
    fill: true,
    tension: 0.1,
    stack: "stack1",
    order: 1,
    pointRadius: 0,
    pointHoverRadius: 5,
    pointBackgroundColor: "rgba(164, 130, 64, 1)",
  },
};

export default placementStyles;
